### PR TITLE
added my 404 page

### PR DESCRIPTION
**Pull request by BinukaDs**
added my 404 page :)

### CODE REVIEW

**Comment by godnondsilva** [comment]
Please add your name to the CONTRIBUTORS.md file as well
@BinukaDs

**Comment by BinukaDs** [comment]
> Please add your name to the CONTRIBUTORS.md file as well @BinukaDs

added :)

**Comment by godnondsilva** [comment]
I'm sorry, I cannot find that change, could you check again?
@BinukaDs 

image

**Comment by BinukaDs** [comment]
I think its ready now :)

**Comment by godnondsilva** [comment]
Thanks!

**Pull request merged**
