### PR TITLE
added a 404 page

### PR DESCRIPTION
**Pull request by emmydev9**
i have added a 404 error page.

### CODE REVIEW

**Review by godnondsilva — CHANGES_REQUESTED** [review]
Refer to the README.md file and make the following changes:
- Add an icon of the final result (icon.png) 
- Add your name to the CONTRIBUTORS.md file as well

**Comment by emmydev9** [comment]
changes made please review

**Review by godnondsilva — APPROVED** [review]
Thanks! Looks great!

**Comment by emmydev9** [comment]
oh Thank you

**Pull request merged**
